version: '3.6'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - devops

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - devops

volumes:
  db:

networks:
  devops:
    external: true